apiVersion: apps/v1
kind: Deployment
metadata:
  name: meta-prod-deployment
  namespace: meta
  labels:
    app: meta-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-prod
  template:
    metadata:
      labels:
        app: meta-prod
    spec:
      containers:
        - name: meta-prod
          image: 043660568366.dkr.ecr.ap-northeast-1.amazonaws.com/taiwan-backend:v0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 11204
              name: https
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
          env:
            - name: API_VERSION
              valueFrom:
                secretKeyRef:
                  name: meta-backend
                  key: API_VERSION
            - name: page_id
              valueFrom:
                secretKeyRef:
                  name: meta-backend
                  key: page_id
            - name: page_access_token
              valueFrom:
                secretKeyRef:
                  name: meta-backend
                  key: page_access_token
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
      dnsPolicy: ClusterFirst
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-worknode-c6a-2xl
