apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-ingress-prod
  namespace: meta
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: \"true\"
spec:
  tls:
    - hosts:
        - meta.tw
      secretName: meta-tls
  rules:
    - host: api.meta.tw
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meta-svc-prod
                port: 
                  number: 11204