apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: meta-ingress-staging
  namespace: meta
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: \"true\"
    nginx.ingress.kubernetes.io/proxy-body-size: 3m
spec:
  tls:
    - hosts:
        - star-bit.io
      secretName: starbit-tls
  rules:
    - host: api-meta.star-bit.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meta-svc-staging
                port: 
                  number: 11204
