kind: Service
apiVersion: v1
metadata:
  name: meta-svc-staging
  namespace: meta
  labels:
    app: meta-staging
spec:
  selector:
    app: meta-staging
  type: NodePort
  ports:
    - name: http
      port: 11204